-- ============================================================
-- Proyecto: Migración MySQL db_fondos_midas -> PostgreSQL
-- Archivo : 02_create_staging_tables.sql
-- Objetivo: Crear tablas intermedias en schema staging
-- Motor   : PostgreSQL
-- ============================================================


-- ============================================================
-- Tabla: staging.saldos_variacion_diaria
-- Descripción:
-- Tabla intermedia para registrar variaciones diarias de saldos.
-- ============================================================

CREATE TABLE IF NOT EXISTS staging.saldos_variacion_diaria (
    id_variacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_saldo DATE NOT NULL,
    codigo_persona VARCHAR(50) NOT NULL,
    numero_cuenta VARCHAR(50) NOT NULL,
    codigo_producto INTEGER NOT NULL,
    nombre_producto VARCHAR(150) NULL,
    saldo_anterior NUMERIC(20,6) NULL,
    saldo_actual NUMERIC(20,6) NOT NULL,
    diferencia NUMERIC(20,6) NOT NULL,
    participaciones_anterior NUMERIC(20,8) NULL,
    participaciones_actual NUMERIC(20,8) NULL,
    clasificacion VARCHAR(20) NOT NULL,
    id_saldo_origen VARCHAR(150) NULL,
    id_lote BIGINT NOT NULL,
    fecha_procesamiento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE staging.saldos_variacion_diaria IS
'Tabla staging para variaciones diarias de saldos migrada desde MySQL db_fondos_midas.saldos_variacion_diaria.';


-- ============================================================
-- Tabla: staging.movimientos_diarios_resumen
-- Descripción:
-- Resumen diario de aportes, retiros y saldo actual.
-- ============================================================

CREATE TABLE IF NOT EXISTS staging.movimientos_diarios_resumen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    codigo_persona VARCHAR(50) NOT NULL,
    nombre_cliente VARCHAR(255) NULL,
    numero_cuenta VARCHAR(50) NOT NULL,
    codigo_producto INTEGER NOT NULL,
    aportes_dia NUMERIC(18,2) NULL DEFAULT 0.00,
    retiros_dia NUMERIC(18,2) NULL DEFAULT 0.00,
    cantidad_aportes INTEGER NULL DEFAULT 0,
    cantidad_retiros INTEGER NULL DEFAULT 0,
    saldo_actual NUMERIC(18,2) NULL,
    fecha_saldo_actual DATE NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE staging.movimientos_diarios_resumen IS
'Tabla staging para resumen diario de movimientos, aportes, retiros y saldo actual.';


-- ============================================================
-- Tabla: staging.stg_comisiones_unificadas
-- Descripción:
-- Tabla staging para consolidar comisiones desde distintas fuentes.
-- ============================================================

CREATE TABLE IF NOT EXISTS staging.stg_comisiones_unificadas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuente VARCHAR(20) NULL,
    anio INTEGER NULL,
    cartera VARCHAR(50) NULL,
    codigoPersona VARCHAR(50) NULL,
    codigoProducto INTEGER NULL,
    comision NUMERIC(18,2) NULL,
    fecha_calculo TIMESTAMP NULL,
    fecha_evento DATE NULL,
    gerente VARCHAR(200) NULL,
    mes INTEGER NULL,
    numeroCuenta VARCHAR(50) NULL,
    saldo_promedio_calendario NUMERIC(18,2) NULL,
    suma_saldos_diarios NUMERIC(18,2) NULL,
    tipo_movimiento VARCHAR(50) NULL,
    usuario_calculo VARCHAR(50) NULL,
    nombreCliente VARCHAR(250) NULL,
    nombreProducto VARCHAR(50) NULL
);

COMMENT ON TABLE staging.stg_comisiones_unificadas IS
'Tabla staging para consolidar comisiones de liquidez, plazo, CAFIF, FPFQ u otras fuentes.';