-- ============================================================
-- Proyecto: Migración MySQL db_fondos_midas -> PostgreSQL
-- Archivo : 03_create_curated_tables.sql
-- Objetivo: Crear tablas analíticas finales en schema curated
-- Motor   : PostgreSQL
-- ============================================================


-- ============================================================
-- Tabla: curated.dim_fecha
-- ============================================================

CREATE TABLE IF NOT EXISTS curated.dim_fecha (
    fecha DATE NOT NULL PRIMARY KEY,
    anio INTEGER NULL,
    mes INTEGER NULL,
    dia INTEGER NULL,
    nombre_mes VARCHAR(20) NULL,
    nombre_dia VARCHAR(20) NULL,
    dia_sem INTEGER NULL,
    dia_anio INTEGER NULL,
    semana INTEGER NULL,
    trimestre INTEGER NULL,
    es_fin_de_mes SMALLINT NULL,
    es_fin_de_anio SMALLINT NULL,
    es_fin_de_semana SMALLINT NULL
);

COMMENT ON TABLE curated.dim_fecha IS
'Dimensión calendario para análisis temporal.';


-- ============================================================
-- Tabla: curated.config_comisiones_plazo
-- ============================================================

CREATE TABLE IF NOT EXISTS curated.config_comisiones_plazo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cartera VARCHAR(50) NOT NULL,
    tipo_movimiento VARCHAR(50) NULL,
    producto VARCHAR(20) NOT NULL,
    beneficiario VARCHAR(20) NOT NULL,
    porcentaje_comision NUMERIC(6,5) NOT NULL,
    prioridad INTEGER NOT NULL DEFAULT 10,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NULL,
    activo SMALLINT NULL DEFAULT 1,
    observaciones TEXT NULL,
    fecha_creacion TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion VARCHAR(50) NULL
);

COMMENT ON TABLE curated.config_comisiones_plazo IS
'Configuración de reglas y porcentajes para cálculo de comisiones de plazo.';


-- ============================================================
-- Tabla: curated.saldos_ultimo_estado
-- ============================================================

CREATE TABLE IF NOT EXISTS curated.saldos_ultimo_estado (
    codigo_persona VARCHAR(50) NOT NULL,
    numero_cuenta VARCHAR(50) NOT NULL,
    codigo_producto INTEGER NOT NULL,
    nombre_producto VARCHAR(150) NULL,
    fecha_ultimo_saldo DATE NOT NULL,
    saldo_ultimo NUMERIC(20,6) NOT NULL,
    participaciones NUMERIC(20,8) NULL,
    valor_participacion NUMERIC(20,10) NULL,
    id_saldo_origen VARCHAR(150) NULL,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_saldos_ultimo_estado 
        PRIMARY KEY (codigo_persona, numero_cuenta, codigo_producto)
);

COMMENT ON TABLE curated.saldos_ultimo_estado IS
'Último saldo conocido por cliente, cuenta y producto.';


-- ============================================================
-- Tabla: curated.saldos_promedio_mensual_hist
-- ============================================================

CREATE TABLE IF NOT EXISTS curated.saldos_promedio_mensual_hist (
    codigopersona VARCHAR(50) NOT NULL,
    numerocuenta VARCHAR(50) NOT NULL,
    codigoproducto INTEGER NOT NULL,
    anio SMALLINT NOT NULL,
    mes SMALLINT NOT NULL,
    periodo_codigo VARCHAR(10) NOT NULL,
    fecha_inicio_mes DATE NOT NULL,
    fecha_fin_mes DATE NOT NULL,
    fecha_apertura_cuenta DATE NULL,
    saldo_promedio_calendario NUMERIC(20,10) NULL,
    suma_saldos_diarios NUMERIC(30,2) NULL,
    divisor_usado SMALLINT NOT NULL,
    es_mes_cerrado SMALLINT NOT NULL,
    fecha_calculo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP NULL,
    usuario_calculo VARCHAR(50) NULL,
    comision NUMERIC(18,2) NOT NULL,
    tipo_movimiento VARCHAR(20) NULL,
    gerente VARCHAR(200) NULL,
    cartera VARCHAR(30) NULL,
    nombreproducto VARCHAR(20) NULL,
    nombrecliente VARCHAR(250) NULL,
    nombrecuenta VARCHAR(255) NULL,
    comision_p NUMERIC(6,4) NULL,
    tipo_registro VARCHAR(25) NULL,

    CONSTRAINT pk_saldos_promedio_mensual_hist 
        PRIMARY KEY (codigopersona, numerocuenta, codigoproducto, anio, mes)
);

COMMENT ON TABLE curated.saldos_promedio_mensual_hist IS
'Histórico mensual de saldos promedio por cliente, cuenta, producto y periodo.';


-- ============================================================
-- Tabla: curated.saldos_promedio_mensual_metas
-- ============================================================

CREATE TABLE IF NOT EXISTS curated.saldos_promedio_mensual_metas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo VARCHAR(7) NOT NULL,
    anio SMALLINT NOT NULL,
    mes SMALLINT NOT NULL,
    cartera VARCHAR(15) NULL,
    gerente VARCHAR(200) NULL,
    nombreproducto VARCHAR(20) NOT NULL,
    sumasaldo NUMERIC(20,10) NULL,
    saldopromedio NUMERIC(30,8) NULL,
    porcentaje NUMERIC(7,5) NULL,
    ingreso NUMERIC(30,8) NULL,
    tipo_registro VARCHAR(25) NOT NULL,
    fecha_inicio_mes DATE NOT NULL,
    fecha_fin_mes DATE NOT NULL,
    diastranscurridosmes SMALLINT NOT NULL,
    diastotalesmes SMALLINT NOT NULL,
    fecha_calculo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP NULL,
    usuario_calculo VARCHAR(50) NULL,
    empresa_de_grupo_idc VARCHAR(5) NOT NULL,

    CONSTRAINT uq_metas_grano UNIQUE (
        anio,
        mes,
        nombreproducto,
        cartera,
        gerente,
        empresa_de_grupo_idc,
        tipo_registro
    )
);

COMMENT ON TABLE curated.saldos_promedio_mensual_metas IS
'Tabla analítica de metas e ingresos derivados de saldos promedio mensuales.';


-- ============================================================
-- Tabla: curated.cliente_producto_historial
-- ============================================================

CREATE TABLE IF NOT EXISTS curated.cliente_producto_historial (
    codigopersona VARCHAR(50) NOT NULL,
    numerocuenta INTEGER NOT NULL,
    codigoproducto INTEGER NOT NULL,
    fecha_primera_posicion DATE NOT NULL,
    saldo_primera_posicion NUMERIC(18,2) NOT NULL,
    participaciones_iniciales NUMERIC(20,8) NULL,
    valor_participacion_inicial NUMERIC(20,8) NULL,
    fecha_ultima_posicion DATE NOT NULL,
    saldo_ultimo NUMERIC(18,2) NOT NULL,
    participaciones_ultimas NUMERIC(20,8) NULL,
    valor_participacion_ultimo NUMERIC(20,8) NULL,
    cuenta_producto VARCHAR(100) NULL,
    edad_apertura_cliente INTEGER NULL,

    CONSTRAINT pk_cliente_producto_historial 
        PRIMARY KEY (codigopersona, numerocuenta, codigoproducto)
);

COMMENT ON TABLE curated.cliente_producto_historial IS
'Historial de primera y última posición de cliente por cuenta y producto.';


-- ============================================================
-- Tabla: curated.clientes_nuevos_fondos
-- ============================================================

CREATE TABLE IF NOT EXISTS curated.clientes_nuevos_fondos (
    anio SMALLINT NOT NULL,
    mes SMALLINT NOT NULL,
    cartera VARCHAR(150) NULL,
    gerente VARCHAR(150) NULL,
    tipo_cliente VARCHAR(100) NULL,
    tipopersona VARCHAR(50) NULL,
    codigopersona VARCHAR(50) NOT NULL,
    nombrecliente VARCHAR(255) NULL,
    fecha_aparicion DATE NOT NULL,
    registros_mes_entrada BIGINT NOT NULL DEFAULT 0,
    clientes_nuevos SMALLINT NOT NULL DEFAULT 1,

    CONSTRAINT pk_clientes_nuevos_fondos PRIMARY KEY (codigopersona)
);

COMMENT ON TABLE curated.clientes_nuevos_fondos IS
'Clientes nuevos identificados por periodo, cartera y gerente.';


-- ============================================================
-- Tabla: curated.fact_comisiones_core
-- ============================================================

CREATE TABLE IF NOT EXISTS curated.fact_comisiones_core (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comision_uid VARCHAR(64) NOT NULL UNIQUE,
    periodo_codigo VARCHAR(7) NOT NULL,
    fecha_evento DATE NOT NULL,
    producto VARCHAR(10) NOT NULL,
    codigo_persona VARCHAR(50) NULL,
    numero_cuenta VARCHAR(50) NULL,
    fondo_id BIGINT NULL,
    tipo_evento VARCHAR(50) NOT NULL,
    grupo_evento VARCHAR(50) NULL,
    cartera VARCHAR(50) NULL,
    gerente VARCHAR(200) NULL,
    tipo_movimiento_comision VARCHAR(20) NULL,
    beneficiario VARCHAR(20) NOT NULL,
    porcentaje_comision NUMERIC(6,5) NOT NULL,
    base_comision NUMERIC(18,2) NOT NULL DEFAULT 0.00,
    comision NUMERIC(20,2) NOT NULL DEFAULT 0.00,
    nombre_inversionista VARCHAR(250) NULL,
    nombrecuenta VARCHAR(255) NULL,
    participaciones_balance_principal NUMERIC(18,6) NULL,
    valor_participacion NUMERIC(18,6) NULL,
    fuente VARCHAR(20) NOT NULL,
    fecha_carga TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE curated.fact_comisiones_core IS
'Tabla fact principal de comisiones consolidadas por evento, producto, beneficiario y fuente.';


-- ============================================================
-- Tabla: curated.fact_comisiones_liquidos_det
-- ============================================================

CREATE TABLE IF NOT EXISTS curated.fact_comisiones_liquidos_det (
    comision_uid VARCHAR(64) NOT NULL PRIMARY KEY,
    codigoproducto INTEGER NULL,
    anio SMALLINT NULL,
    mes SMALLINT NULL,
    fecha_inicio_mes DATE NULL,
    fecha_fin_mes DATE NULL,
    saldo_promedio_calendario NUMERIC(20,10) NULL,
    suma_saldos_diarios NUMERIC(30,2) NULL,
    divisor_usado SMALLINT NULL,
    dias_calculo INTEGER NULL,
    es_mes_cerrado SMALLINT NULL,
    regla_id INTEGER NULL,
    regla_fecha_inicio DATE NULL,
    regla_fecha_fin DATE NULL,
    tipo_registro VARCHAR(25) NULL,
    usuario_calculo VARCHAR(50) NULL,
    fecha_calculo TIMESTAMP NULL
);

COMMENT ON TABLE curated.fact_comisiones_liquidos_det IS
'Detalle de comisiones de fondos líquidos asociado a fact_comisiones_core.';


-- ============================================================
-- Tabla: curated.comisiones_plazo_hist
-- ============================================================

CREATE TABLE IF NOT EXISTS curated.comisiones_plazo_hist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento VARCHAR(200) NOT NULL UNIQUE,
    tipo_evento VARCHAR(20) NOT NULL,
    fecha_evento DATE NOT NULL,
    anio INTEGER NOT NULL,
    mes SMALLINT NOT NULL,
    trimestre SMALLINT NOT NULL,
    codigopersona VARCHAR(50) NULL,
    numerocuenta VARCHAR(50) NULL,
    codigoproducto INTEGER NULL,
    nombreproducto VARCHAR(50) NOT NULL,
    nombrecliente VARCHAR(200) NULL,
    monto_base NUMERIC(18,2) NOT NULL,
    porcentaje_comision NUMERIC(10,6) NOT NULL,
    comision NUMERIC(18,2) NOT NULL,
    tipo_cliente VARCHAR(50) NULL,
    tipo_movimiento VARCHAR(50) NULL,
    cartera VARCHAR(50) NULL,
    gerente VARCHAR(150) NULL,
    fuente_registro VARCHAR(50) NOT NULL,
    fecha_calculo TIMESTAMP NOT NULL,
    usuario_calculo VARCHAR(50) NOT NULL
);

COMMENT ON TABLE curated.comisiones_plazo_hist IS
'Histórico de comisiones de plazo por evento, cliente, producto y periodo.';


-- ============================================================
-- Tabla: curated.cafif_fondos
-- ============================================================

CREATE TABLE IF NOT EXISTS curated.cafif_fondos (
    fondoid VARCHAR(60) NOT NULL PRIMARY KEY,
    codpersona VARCHAR(60) NOT NULL,
    nombreinv VARCHAR(200) NULL,
    nombrecuenta VARCHAR(200) NULL,
    producto VARCHAR(80) NULL,
    cartera VARCHAR(60) NULL,
    tipomovimientocomision VARCHAR(30) NULL,
    gerente VARCHAR(120) NULL,
    fechainversion DATE NOT NULL,
    montoaporteinicial NUMERIC(18,2) NOT NULL,
    participacionesiniciales NUMERIC(18,6) NOT NULL,
    valorparticipacionentrada NUMERIC(18,9) NOT NULL,
    fecha_aniversario DATE NOT NULL,
    fecha_cancel_total DATE NULL,
    tipo_cancelacion VARCHAR(50) NULL,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE curated.cafif_fondos IS
'Fondos CAFIF identificados para cálculo y seguimiento de comisiones.';


-- ============================================================
-- Tabla: curated.cafif_comision_mensual
-- ============================================================

CREATE TABLE IF NOT EXISTS curated.cafif_comision_mensual (
    periodopagado CHAR(7) NOT NULL,
    fecha_corte DATE NULL,
    fondoid VARCHAR(60) NOT NULL,
    codpersona VARCHAR(60) NOT NULL,
    nombreinv VARCHAR(200) NULL,
    nombrecuenta VARCHAR(200) NULL,
    producto VARCHAR(80) NULL,
    cartera VARCHAR(60) NULL,
    tipomovimientocomision VARCHAR(30) NULL,
    gerente VARCHAR(120) NULL,
    participaciones NUMERIC(18,2) NOT NULL,
    valorparticipacion NUMERIC(18,9) NOT NULL,
    montobase NUMERIC(18,2) NOT NULL,
    beneficiario VARCHAR(20) NOT NULL,
    comisionpct NUMERIC(10,6) NOT NULL,
    dias INTEGER NOT NULL,
    tipo_registro VARCHAR(50) NOT NULL,
    estadofondo VARCHAR(20) NOT NULL,
    fecha_aniversario DATE NULL,
    tipo_cancelacion VARCHAR(50) NULL,
    fecha_cancel_total DATE NULL,
    comisionlc NUMERIC(18,2) NOT NULL,

    CONSTRAINT pk_cafif_comision_mensual
        PRIMARY KEY (periodopagado, fondoid, beneficiario, tipo_registro)
);

COMMENT ON TABLE curated.cafif_comision_mensual IS
'Comisión mensual CAFIF por periodo, fondo, beneficiario y tipo de registro.';