-- ============================================================
-- Proyecto: Migración MySQL db_fondos_midas -> PostgreSQL
-- Archivo : 04_create_audit_tables.sql
-- Objetivo: Crear tablas de auditoría y control ETL
-- Motor   : PostgreSQL
-- ============================================================


-- ============================================================
-- Tabla: audit.etl_control
-- Descripción:
-- Control de última ejecución por entidad/proceso.
-- ============================================================

CREATE TABLE IF NOT EXISTS audit.etl_control (
    entity_name TEXT NULL,
    last_run TIMESTAMP NULL,
    last_since TEXT NULL,
    last_status TEXT NULL,
    last_rows_processed INTEGER NULL
);

COMMENT ON TABLE audit.etl_control IS
'Tabla de control de última ejecución por entidad o proceso ETL.';

COMMENT ON COLUMN audit.etl_control.entity_name IS
'Nombre lógico de la entidad, tabla o proceso controlado.';

COMMENT ON COLUMN audit.etl_control.last_run IS
'Fecha y hora de la última ejecución registrada.';

COMMENT ON COLUMN audit.etl_control.last_status IS
'Estado de la última ejecución del proceso.';


-- ============================================================
-- Tabla: audit.etl_run_logs
-- Descripción:
-- Bitácora de ejecuciones ETL.
-- ============================================================

CREATE TABLE IF NOT EXISTS audit.etl_run_logs (
    run_id TEXT NULL,
    entity_name TEXT NULL,
    start_time TIMESTAMP NULL,
    end_time TIMESTAMP NULL,
    status TEXT NULL,
    rows_processed INTEGER NULL,
    error_msg TEXT NULL
);

COMMENT ON TABLE audit.etl_run_logs IS
'Bitácora de ejecuciones ETL con tiempos, estado, cantidad de registros y errores.';

COMMENT ON COLUMN audit.etl_run_logs.run_id IS
'Identificador de la ejecución del proceso ETL.';

COMMENT ON COLUMN audit.etl_run_logs.entity_name IS
'Nombre lógico de la entidad procesada.';

COMMENT ON COLUMN audit.etl_run_logs.error_msg IS
'Mensaje de error registrado durante la ejecución, si aplica.';


-- ============================================================
-- Tabla: audit.saldos_control_lotes
-- Descripción:
-- Control de lotes para procesamiento de saldos.
-- ============================================================

CREATE TABLE IF NOT EXISTS audit.saldos_control_lotes (
    id_lote BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_desde DATE NOT NULL,
    fecha_hasta DATE NOT NULL,
    estado VARCHAR(20) NOT NULL,
    registros_origen INTEGER NOT NULL DEFAULT 0,
    registros_variacion INTEGER NOT NULL DEFAULT 0,
    registros_estado INTEGER NOT NULL DEFAULT 0,
    fecha_inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_fin TIMESTAMP NULL,
    mensaje_error TEXT NULL,
    ejecutado_por VARCHAR(100) NULL
);

COMMENT ON TABLE audit.saldos_control_lotes IS
'Tabla de control de lotes para procesamiento de saldos, variaciones y último estado.';

COMMENT ON COLUMN audit.saldos_control_lotes.id_lote IS
'Identificador único del lote de procesamiento.';

COMMENT ON COLUMN audit.saldos_control_lotes.estado IS
'Estado del lote: iniciado, procesado, cerrado, error u otro valor operativo.';

COMMENT ON COLUMN audit.saldos_control_lotes.registros_origen IS
'Cantidad de registros origen considerados en el lote.';

COMMENT ON COLUMN audit.saldos_control_lotes.registros_variacion IS
'Cantidad de registros generados en variación diaria.';

COMMENT ON COLUMN audit.saldos_control_lotes.registros_estado IS
'Cantidad de registros actualizados en último estado.';